sudo: required
services:
  - docker
before_install:
  - docker build -t mosipadp/test .
script:
  - docker images mosipadp/test

before_deploy:
  - docker login -u="mosipadp" -p="2fT&(cEHYRML8Wu"

deploy:
    docker push mosipadp/test