sudo: required
services:
  - docker
script:
  - docker build -t dingane/test .
  - docker images dingane/test

before_deploy:
  - docker login -u="mosipadp" -password="2fT&(cEHYRML8Wu"

deploy:
  provider: script
  script: docker push mosipadp/test
  on:
    branch: master

